### PR TITLE
Solved UglifyJS compile issues. Fixes #1

### LINKED ISSUE #1: ERROR from UglifyJs
Hey man, first of all GREAT PLUGIN, thanks!

It works great with webpack in dev but it has a problem with the UglifyJs when compressing.
Here is the ouput
```
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/vue-online/src/VueOnline.js:4,0][build.js:22879,9]
```
When the `VueOnline.js` data function is changed to 
```
data: function () {
      return {
        isOnline: true
      }
    }
```
it solves the above but outputs
```
ERROR in build.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:» [./~/vue-online/main.js:3,18][build.js:37812,35]
```
Didn't figure out how to get out of that. Any suggestion? :)

### PR DESCRIPTION
**Pull request by mikemassari**
This should fix the issue I previously raised about UglifyJS.

Testes in the browser with a Vue installation using the webpacks-simple template

### CODE REVIEW

**Comment by Sopamo** [comment]
Ah, okay that's just an ecma script 6 issue, I'll merge your pull request in because it doesn't really change much, but maybe I should add some documentation in the future how to setup webpack with babel. Or setup a build process to do the babelify stuff for the distribution files automatically.
Nevertheless, thanks for your pull request, it makes things easier for now :)

**Comment by kharysharpe** [comment]
Hey @Sopamo,

Did you publish this to npm?

Still getting the old code :(

**Comment by Sopamo** [comment]
Sorry, I forgot to publish it over the holidays. It's now online on npm :)

**Comment by kharysharpe** [comment]
Great :)
Thank you for creating this.

**Pull request merged**
